### ISSUE TITLE
What do you use for your site/blog?

### ISSUE THREAD

**Issue by gigocabrera** [juristr/ama#1]
@juristr I just read your article "Kudos for your site" (awesome by the way) and I was wondering:
1) Is your site/blog using Firebase as the backend? 
2) Was your site/blog developed by you or is it from an open source framework?
I'm a .NET developer who's transitioning to the Front-end (still a newbie) and I'm looking for an open source site/blog that I can use for my personal site/blog.
Thanks!

**Comment by juristr** [comment]
hi @gigocabrera,

nice u found my AMA :smile: . You're the first!

Actually I'm using [Jekyll](https://jekyllrb.com/) for blogging, together with [GitHub Pages](https://pages.github.com/). Always wanted to publish a post on how that works, but never did. But anyway, there's lots of documentation around.

Jekyll is a static website/blog generator. You basically write your posts/sites in [Markdown](https://daringfireball.net/projects/markdown/) syntax, which is quite popular and very easy to learn/use for writing. Then Jekyll takes the responsibility of converting those Markdown files into HTML files. In my case, those files are served by GitHub pages.

> 1) Is your site/blog using Firebase as the backend? 

The blog doesn't use it, as you don't need any database, just plain text files stored on GitHub. My blog is being produced out of this repo: [juristr.github.com](https://github.com/juristr/juristr.github.com). Publishing a new post is as easy as committing a new file to that repo.

 I use Firebase for the Kudos plugin to store the kudos as they're something dynamic.

> 2) Was your site/blog developed by you or is it from an open source framework?

As you now probably know, Jekyll does most of the job. I did the CSS, the JavaScript for some dynamic behavior etc.

---

Here are some links to get started with Jekyll
- [https://jekyllrb.com/](https://jekyllrb.com/)
- [GitHub: Blogging with Jekyll](https://help.github.com/articles/using-jekyll-with-pages/)
- [Custom domain with Jekyll and GitHub Pages](https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages/)

Hope I was able to help :smile: 

Cheers
Juri

**Comment by gigocabrera** [comment]
@juristr that's awesome thank you. 
By the way, I had the great opportunity to go to Bolsano back in 2007 with my Dad to visit friends and loved it. I celebrated my 40th birthday there...

**Comment by juristr** [comment]
@gigocabrera You mean [Bolzano, Italy](https://www.google.it/maps/place/Bolzano,+Province+of+Bolzano+-+South+Tyrol/@46.4877528,11.2845562,12z/data=!3m1!4b1!4m2!3m1!1s0x47829dda10e53439:0x407098715913070?hl=en)??

**Comment by gigocabrera** [comment]
@juristr yes Bolzano, Italy, and visited the museum with Ötzi, the ice man. It was awesome!

**Comment by juristr** [comment]
@gigocabrera cool :+1:
