### ISSUE TITLE
Chrome is giving the Failed to execute 'setRequestHeader' on 'XMLHttpRequest': 'Authorization: Bearer ' is not a valid HTTP header field name 

### ISSUE THREAD

**Issue by vdoolla** [juristr/ama#10]
Environments – Angular2 with CLI + Boot Strap4 is Front End ( localhost:4200)
Spring boot + Security +JWT + REST Ful Controllers for Back End (localhost:8080)

Chrome is giving the Failed to execute 'setRequestHeader' on 'XMLHttpRequest': 'Authorization: Bearer ' is not a valid HTTP header field name the same piece of code is working fine with IE.

I have been breaking my head from last two weeks and did lot of googling and unable to resolve the issue. As I am running out of time I am posting this question here hoping some Angular2 Gods will provide suggestions to resolve this issue.

Environments – Angular2 with CLI + Boot Strap4 is Front End ( localhost:4200)
Spring boot + Security +JWT + REST Ful Controllers for Back End (localhost:8080)

Here is the scenario:
 
Login Screen 
 
![capture](https://cloud.githubusercontent.com/assets/21183106/20571757/c46c8980-b176-11e6-8e43-0d2d27e0cd99.JPG)

 Onsubmit - Passing the Credentials to the Spring Boot Security to Authenticate.
 
 onSubmit() {
     
     this.loginService.authenticateUser(this.loginUserDtls)
     .subscribe( 
	  data => {
		let token=  JSON.parse(JSON.stringify(data))._body;
        console.log("TOKEN  VALUE "+token) ;
   		this.loginService.sendToken(token).subscribe( 
        data => {
			let dataRet=  JSON.parse(JSON.stringify(data))._body;
			console.log("data received  "+dataRet);
         }
        )
        
     });
 On Successful authentication Spring Security generating the JWT Token   and sending the token back to fort end keeping it in the response header as below 
 
  response.addHeader("Authorization", "Bearer " + JWT);
  
 Issue 1- 
 Some reason Angular 2 (localhost:4200) response header is missing the Authorization header details   which is placed in the Spring Boot Security Services (localhost:8080)

For Issue 1- I had a workaround by sending the JWT token in the response body. 

After extracting the token the from response body, I am invoking a different restful service by passing token in the Angular 2 request Header as below :

sendToken(token)  {

    var headers = new Headers();
    headers.append('Content-Type', 'application/x-www-form-urlencoded; charset=UTF-8');
    headers.append('Authorization', 'Bearer '+ token);
    headers.append('Accept', 'application/json');

    return this.http.get('http://localhost:8082/users', {headers:headers});
     
 }
 
The above worked is working fine in IE but when testing the same thing in Chrome getting  the 
 Failed to execute 'setRequestHeader' on 'XMLHttpRequest': 'Authorization: Bearer ' is not a valid HTTP header field name. Also please verify the screenshot for more detailed console log.
 
 I had tried the above code with RequestOptions withCredentials = true also but no luck with Chrome.
 
 Please kindly post your suggestions to resolve the issue.

**Comment by juristr** [comment]
Hey, I'm sorry, but I somehow missed your post here. I've seen you've also posted on the CLI GitHub repository: https://github.com/angular/angular-cli/issues/3253

Not sure whether answers there have solved your issue. Anyways. It's really difficult to help here, also because I never used JWT tokens with Spring Boot. To be able to help you'd have to share some GitHub repo or something which I can run in order to better understand the issue.

What I would do is to try sending custom tokens myself and trying to read them on the backend. Like injecting a token "Bearer" but with a very simple value, a short string or something. And then test whether that one works.

The error message very much indicates a problem with the header value.

**Comment by vdoolla** [comment]
Hi, Thank you for your response.  I am able to resolve this issue. This issue is due to CORS. Chrome is making a preflight and server is not setting header due to this during actual call chrome is not able to recognize Authorization header. Hence closing this.
