### ISSUE TITLE
How would you white label an Angular 2 application?

### ISSUE THREAD

**Issue by calloncampbell** [juristr/ama#11]
If a client asked you to create an Angular 2 app and wanted it white labelled (Brand A, Brand B, Brand C), how would you go about tackling this request?

My requirement is that I would have a generic login screen and once the user logged in, they would be redirected to the app with their specific branding (logo, colors, etc). I would also want to handle subdomains, so BrandA.myapp.com, BrandB.myapp.com, etc.

Appreciate any guidance or references.

Thanks
Callon

**Comment by juristr** [comment]
@calloncampbell :scream: I totally missed this one, I'm sorry! Not sure if you still need it, but I'll try to answer quickly.

First of all, the problem can be tackled in a variety of ways. It very much depends on your overall architecture and requirements you're having. Let me try..

> ...and wanted it white labelled (Brand A, Brand B, Brand C), how would you go about tackling this request?

That could be done through some configuration, which could be JSON or JS files containing keys containing textual info as well as flags for "configuring" the app...for instance

```
// branda-config.js
{
  appTitle: 'Brand A',
  showLogo: false,
  ...
}
```

And then you load the configuration you need for the specific brand either at runtime or already when compiling and deploying the app.

> My requirement is that I would have a generic login screen and once the user logged in, they would be redirected to the app with their specific branding (logo, colors, etc). I would also want to handle subdomains, so BrandA.myapp.com, BrandB.myapp.com, etc.

Sounds good overall, the decision of having different subdomains obviously depends on your needs. The only thing you have to pay attention to is for the authentication. I'm not sure how people authenticate, whether there is one authentication system for all apps or different ones. When it comes to authentication you have to make sure to properly account for the different domains, as one domain might not necessarily see the authentication information of the other one. That obviously depends how you configure it (cookie based, visibility of that cooke, or JWT...)
