### ISSUE TITLE
Your article 《Create a dynamic tab component with Angular》

### ISSUE THREAD

**Issue by kkcode24** [juristr/ama#13]
## I failed when I wanted to create a Component on 'about' page and load it onto the original TAB component.

:+1: [hit here to your article](https://juristr.com/blog/2017/07/ng2-dynamic-tab-component/#disqus_thread)

It is best to make an improvement on this basis  ([your plnkr](https://run.plnkr.co/preview/cj7u7zlrn000e3b5qg4p82hdj/))

```
Do you have any good ideas,please let me know,thank you
```

**Comment by juristr** [comment]
@kkcode24 Hey, thx for your comment. I didn't quite get tho how I can help you. Can you please better describe where you're stuck? thx 😄

**Comment by kkcode24** [comment]
@juristr  thx for your reply. Sorry,I'm Chinese,My English is not so good.I used a picture show what I want to do. I hope you can understand.


![picture](https://user-images.githubusercontent.com/23212449/30816898-d221d4e4-a249-11e7-9e77-ca54007d0394.png)

**Comment by kkcode24** [comment]
@juristr  I'm looking forward to your reply soon. Don't wait any longer, please.

**Comment by juristr** [comment]
Hey, no worries about your english.

For doing what you want, you can simply replicate the behavior of the button which is in the 1st tab:
![image](https://user-images.githubusercontent.com/542458/30847200-e44108ce-a29a-11e7-8fdc-8e9c6137977f.png)

And adapt it to your needs.

**Comment by kkcode24** [comment]
Thank you for your help, although it doesn't help

**Comment by kkcode24** [comment]
You don't understand what I mean, [same question in stackoverflow](https://stackoverflow.com/questions/38327724/dynamic-tab-navigation-system-using-angular-2)

**Comment by juristr** [comment]
Oh now I see what you mean. You want to combine this even with the router configuration, s.t. routing changes are also being opened inside another tab etc. 

That's something I've done years ago with another frontend framework based on jQuery and it was quite challenging, but still works on a production application of ours. I've been thinking recently about how to achieve such thing also with Angular and it's new router, but I'm not quite sure it's possible. In any way I'd have to do some further research and do some trials. 

So as of now I'm sorry but cannot much help you other with the example which is already on my blog. Which shows how to programmatically add new components to a dedicated area you define, but obviously it doesn't make use of routing configurations etc. But if you find a solution, let me know, I'm very much interested as well 😄

**Comment by kkcode24** [comment]
Thx for your help,if I find a solution. I will tell you, But if you find a solution, let me know, thanks

**Comment by juristr** [comment]
definitely, I'll ping you here 👍 .

(meanwhile I'm closing this issue)
