### ISSUE TITLE
devenv deployment for SSIS package on visual studio 

### ISSUE THREAD

**Issue by cooldude9089** [juristr/ama#16]
Hi,

Can you please let me know if there is any option to automate SSIS package deployment to database catalog.
I am trying this but is not working, I want to deploy the .dtsx packages to sql server database catalog  
 
& 'C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\devenv.com' pro.sln /deploy /pr
oject ".\pro\pro.dtproj" /projectconfig "Release"

Thanks,

**Comment by juristr** [comment]
hey, thx for the question but unfortunately I'm not an SQLServer expert. Thus I won't be very helpful in answering this question, sorry
