### ISSUE TITLE
what  theme vs code

### ISSUE THREAD

**Issue by xenocent** [juristr/ama#18]
what theme in this video https://www.youtube.com/watch?time_continue=170&v=OjmZPPKaj6A did u use?

**Comment by juristr** [comment]
Hey... 🤔 hmm.. Guess was some material theme and tried the Operator Mono font. But that font costs a lot.

That's why currently I'm using the Night Owl theme + Fira Code as the font. Love it 👍.

Wes Bos also has quite a good one, called cobalt theme (or similar)
