### ISSUE TITLE
Eyes

### ISSUE THREAD

**Issue by Sebastian-Nielsen** [juristr/ama#19]
One of the things I hate the most about having to look at a screen a lot is the strain that it causes on my eyes. 
*Questions*
How often do you feel strain on your eyes?
Do you combat it in any way?

**Comment by juristr** [comment]
Oh, that's a difficult question. To be honest, I don't feel strain on my eyes very often. It occasionally happens. What I usually try to do (in general), is to do some activity outside after work. I work A LOT, so even after work I often spend 2-3 hours working on my other stuff (as I'm also freelancing as a side-job). Still I try to go out, either for a walk in nature, I exercise a lot which helps me stay fresh mentally & relax my brain.

Other suggestions I have

- try to experiment with different brightness settings on you display
- try different themes on your editor. Maybe dark works better, or a light theme. That's really something that's different for each person.
- definitely go to see a doctor and let your eyes check. It might be that you're having "dry eyes" or something else. So it's definitely worth let that check.

Hope I could help 😃
