### ISSUE TITLE
Working at Nrwl from Italy

### ISSUE THREAD

**Issue by trumbitta** [juristr/ama#22]
Hey 👋 I'm Italian, and in love with Nx and Nrwl.

Last time I had the opportunity to work with an international company I had to bail out from the hiring process because taxation in Italy for a P.IVA (without access to special treatments like first-time P.IVA or being under-35yrs old) would have made it almost impossible to earn a living for me and my family.

So I was wondering if you could share some info about your experience with Nrwl, taxes, and family, to help me understand if it's worth it to take my chances and pursue my dream job ✌️

**Comment by juristr** [comment]
Sent you a DM on Twitter. TL;DR: it's tough...unfortunately 😞
