### ISSUE TITLE
Connecting you to a company

### ISSUE THREAD

**Issue by DolGit** [juristr/ama#23]
I met you at an event 2 weeks ago and we hung out but didn't exchange contacts (it was a large group of us). Then 2 days later I met a large company (not corporate but funded and growing) saying they were about to start using Nx. I googled Nx and saw your face. Shall I connect you to them?

**Comment by juristr** [comment]
> I met you at an event 2 weeks ago

Which event?

**Comment by DolGit** [comment]
ModernFrontendsLive, I was the one who led everyone to Canary Wharf on Friday evening and we ate at ShakeShack.

**Comment by juristr** [comment]
👍 nice!

yeah feel free to connect me with them if they need help. 

Here are also some more resources in case:

- Website: https://nx.dev
- Community Slack: https://go.nrwl.io/join-slack
- Nx Enterprise: https://nx.app/enterprise/

**Comment by DolGit** [comment]
Awesome, they're great guys to be in contact with and they're really excited about Nx. Please look out for the intro in your emails. Hopefully see you at another event soon!
