### ISSUE TITLE
Template error/routing error block the navigation

### ISSUE THREAD

**Issue by smedavarapu** [juristr/ama#3]
**Issue**
There is an issue with errors in routerLink blocking the entire routing of the application. Posted the question on Stackoverflow and also realized it is an issue, so posted it in the Github.

**sources**
Please  see the question and comments in Stackoverflow: http://stackoverflow.com/questions/36798103/exception-handling-in-angular-2/36799285#36799285
Github Issue: https://github.com/angular/angular/issues/8211

Thanks for your Time!

**Comment by juristr** [comment]
@smedavarapu Indeed looks like a bug/issue in the Angular routing module. You're better off discussing this on the official GitHub repo as you already did 😃 . I subscribed to that issue. Interested in the root cause.
Maybe I'll find the time to dig into the root cause of it

**Comment by smedavarapu** [comment]
Hey thanks for looking into it @juristr . Nice to have you in the loop.
