### ISSUE TITLE
What blog template are you using?

### ISSUE THREAD

**Issue by christrotter89** [juristr/ama#4]
I love the template your blog uses. Very clear and elegant. Could you please share the template you use?

**Comment by juristr** [comment]
@christrotter89 Sorry for the late answer, I had an issue with GitHub not notifying me about new incoming issues :smile: 

Which template exactly do you mean :smile: , I'm using multiple ones right now. But all of them are basically handcrafted by myself, with inspirations from other blogs, Medium etc.. That's the way I originally learned CSS and I'm still learning this way. I'm seeing something cool, I learn from their CSS and try to implement something similar for myself.

> Could you please share the template you use?

Well it's online, you can grab it when you inspect my page. I even thought to create a reusable Jekyll theme based off my blog's template...but never had the time to do so. I'd basically have to clean up some stuff before doing so
