### ISSUE TITLE
Module '"c:/projects/angular2-quickstart/node_modules/@angular/router/index"' has no exported member 'RouterConfig'. import RouterConfig

### ISSUE THREAD

**Issue by WaqarMH** [juristr/ama#7]
I am getting this error :/

![screenshot_5](https://cloud.githubusercontent.com/assets/13906186/18680614/f917e1aa-7f7d-11e6-8c68-b39840eff8ef.png)

I remove the router 
npm remove @angular/router
And install npm install @angular/router@3.0.0-alpha.7 .. 
After installation of @angular/router@3.0.0-alpha.7 i got this ...
![screenshot_4](https://cloud.githubusercontent.com/assets/13906186/18680575/d1fdf5a0-7f7d-11e6-9571-543ebe9dd364.png)

Node Version: v6.6.0
Npm Version: v3.10.3
OS: Window 8.1

Is there any alternative to solve this problem?

**Comment by juristr** [comment]
Unfortunately I didn't yet do much with the router, or better fortunately as the team changed it 3 times 😄 .

Make sure you upgrade to the latest router version. Not sure which one that is, should be `v3.0.0` I think. Then I'd rather suggest you to take a look at the articles Victor Savkin (core Angular 2 team member) has on his blog: https://vsavkin.com/.
He's an expert in the angular router, also probably 'cause he wrote most of it :wink:.

**Comment by WaqarMH** [comment]
hmm thank you

**Comment by juristr** [comment]
The error you're getting suggests just that, basically that you're using an API which is no more valid for the router package you're importing. `RouteConfig` was present in a previous version of the router I think.

Take a look at these seed projects:
- https://github.com/AngularClass/angular2-webpack-starter
- https://github.com/mgechev/angular2-seed
- eventually also use the Angular CLI and generate a project: https://cli.angular.io/

Those starters have demo projects build-in which usually have the latest versions of angular 2 and most of the packages. Should have updated versions of the router there as well. Check those src files and see how the routing got implemented 👍
