### ISSUE TITLE
package.json

### ISSUE THREAD

**Issue by iwilfried** [juristr/ama#8]

**Comment by juristr** [comment]
Hi @iwilfried, thanks :smiley: 

Let me understand where you started. When exactly does this happen? You mention `npm start`, but
- Did you start from scratch with the Angular CLI, by creating a new project
- or did you clone the repo from the video: https://github.com/juristr/video-your-first-ng2-app

thx

**Comment by iwilfried** [comment]
Hi Juri,

After studying I try to start from scratch without CLI. I started with npm ini
I started from scratch without CLI and tried to copy all the necessary files from the website, to understand better. Started with npm init and then npm install lite-server to run a html file
Now i have this package.json; something is wrong with tsc-w
{
  "name": "angular",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "tsc && concurrently \"npm run tsc:w\" \"npm run lite\"",
    
    "lite": "lite-server",
    "tsc": "tsc",
    "tsc:w": "tsc-w",
    "typings": "typings",
    "postinstall": "typings install"

  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "concurrently": "^3.1.0",
    "lite-server": "^2.2.2",
    "typescript": "^2.0.6",
    "typings": "^1.5.0"
  }
}

**Comment by juristr** [comment]
:open_mouth: what happened?

**Comment by iwilfried** [comment]
Everything ok! I think I should prepare the question better, so that it is not too much work for you. Come back asap and thank you for this fast response.  You can close this issue. I come back .Thank you again
Wilfried
