### ISSUE TITLE
Angular2 vs Polymer

### ISSUE THREAD

**Issue by rahuliet** [juristr/ama#9]
I am working on a project which is basically on visualization of different set of charts with data pulled from JSON structure.The chart generation logic is written in form of a JavaScript library coded using D3.js and vanilla JavaScript. The requirement of project says to expose this library along with a top layer of chart components where in some end user(technical user) will have to simple include this JS file and write something like <xyz-chart></xyz-chart/> .This will be helpful in arranging the charts in different HTML templates according to needs of end user and also this will also add to simplicity while integration with any other Project.

Could you please suggest me what is the best way to do this?

**Comment by juristr** [comment]
Hi @rahuliet. I have to say I'm not an expert in Polymer. I've a bit played around with it, but that's it.

That said, however, Polymer is part of the web component movement, whose intention is to foster re-usability. They aren't native web components tho. Polymer is in some sense a very thin "library/framework" that helps run web component technology on nowadays browsers, just like Angular 2 is, but obviously bigger.

By using Polymer, you would probably guarantee higher re-usability among different kind of frameworks (Angular, React, VanillaJS...). On the other side, if that's not a requirement and you know your library will be used nearly exclusively from within the Angular 2 ecosystem, then you're probably better off creating it with Angular and thus getting out with a better native integration.

So frankly:
- Polymer/web components: higher re-usability for the cost of framework specific integrations
- Angular 2: better native framework integration but hardly re-usable among other frameworks like ReactJS.

I do not have enough experience tho when it comes to reusing Angular 2 components within other frameworks. That's an interesting idea that is for sure worth exploring. Angular 2's latest optimizations make the resulting outcome a really tiny construct, where everything gets compiled into native JavaScript and there isn't much to be left about Angular 2 itself in the compiled script. However, that's something that needs to be explored.

What could be interesting for you is to maybe take a look at the [ng2d3 library](https://github.com/swimlane/ng2d3), which is an Angular 2 library for creating D3.js visualizations.

Hope this helps :smiley:

**Comment by rahuliet** [comment]
This is extremely helpful.Almost I got the direction to move ahead.Primary goal is re-usability and main thrust is develop a lightweight re-usable element.I will look later into Angular 2 offering as this seems to be gaining ground recently.
Thanks I already checked into [ng2d3 ](https://github.com/swimlane/ng2d3) library but it seemed to be somewhat restricted.I don't want to restrict myself on visualization piece of project as this is where real power lies..  :+1:

**Comment by juristr** [comment]
@rahuliet :+1:

**Comment by mohammedzamakhan** [comment]
Need to update this with Angular Elements! 😄

**Comment by juristr** [comment]
@mohammedzamakhan 😊. My Egghead course on Angular Elements is about to be released next week 😉.
Will announce it on Twitter (https://twitter.com/juristr) & on my blog https://juristr.com/blog
